// 增强 vocabulary.ts：
// 1) 拆分混在 word 字段里的音标（形如 "circuit/ˈsɜːrkɪt/"）
// 2) 为真实英文单词补全美式音标（大词典）
// 3) 为缺失例句的真实英文单词补全例句
import fs from 'node:fs';

const src = fs.readFileSync('src/data/vocabulary.ts', 'utf8');

// ---- 美式 IPA 词典（覆盖本项目所有真实英文单词）----
const IPA = {
  "strong correlation": "/strɔːŋ ˌkɑːrəˈleɪʃən/",
  "desired": "/dɪˈzaɪərd/",
  "pullup resistor": "/ˈpʊlˌʌp rɪˈzɪstər/",
  "bias resistor": "/ˈbaɪəs rɪˈzɪstər/",
  "pull down resistor": "/pʊl daʊn rɪˈzɪstər/",
  "series resistor": "/ˈsɪriːz rɪˈzɪstər/",
  "input ac couple capacitor": "/ˈɪnpʊt eɪ siː ˈkʌpəl kəˈpæsɪtər/",
  "high common mode noise rejection ratio": "/haɪ ˈkɑːmən moʊd nɔɪz rɪˈdʒekʃən ˈreɪʃioʊ/",
  "amplifier": "/ˈæmplɪfaɪər/",
  "isolation": "/ˌaɪsəˈleɪʃən/",
  "beads": "/biːdz/",
  "capacitor rated voltage": "/kəˈpæsɪtər ˈreɪtɪd ˈvoʊltɪdʒ/",
  "dc resistance": "/diː siː rɪˈzɪstəns/",
  "impedance": "/ɪmˈpiːdəns/",
  "zener voltage": "/ˈzeɪnər ˈvoʊltɪdʒ/",
  "rated power": "/ˈreɪtɪd ˈpaʊər/",
  "zener diode": "/ˈzeɪnər ˈdaɪoʊd/",
  "relay": "/ˈriːleɪ/",
  "coil": "/kɔɪl/",
  "short to battery diagnostic and protection": "/ʃɔːrt tuː ˈbætəri ˌdaɪəɡˈnɑːstɪk ænd prəˈtekʃən/",
  "power supply filter capacitor": "/ˈpaʊər səˈplaɪ ˈfɪltər kəˈpæsɪtər/",
  "filter": "/ˈfɪltər/",
  "rated voltage": "/ˈreɪtɪd ˈvoʊltɪdʒ/",
  "insufficient": "/ˌɪnsəˈfɪʃənt/",
  "partitioning": "/pɑːrˈtɪʃənɪŋ/",
  "decoupling capacitor": "/diːˈkʌplɪŋ kəˈpæsɪtər/",
  "non-optimal power plane partitioning": "/nɑːnˈɑːptɪməl ˈpaʊər pleɪn pɑːrˈtɪʃənɪŋ/",
  "circuit": "/ˈsɜːrkɪt/",
  "alternative": "/ɔːlˈtɜːrnətɪv/",
  "sync up": "/sɪŋk ʌp/",
  "prior": "/ˈpraɪər/",
  "indication": "/ˌɪndɪˈkeɪʃən/",
  "capable": "/ˈkeɪpəbəl/",
  "deficiencies": "/dɪˈfɪʃənsiz/",
  "innovation": "/ˌɪnəˈveɪʃən/",
  "filed performance": "/fiːld pərˈfɔːrməns/",
  "field": "/fiːld/",
  "determine": "/dɪˈtɜːrmɪn/",
  "excitation": "/ˌeksɪˈteɪʃən/",
  "generated": "/ˈdʒenəreɪtɪd/",
  "maintain": "/meɪnˈteɪn/",
  "acount": "/əˈkaʊnt/",
  "upgrade": "/ˈʌpɡreɪd/",
  "peripheral": "/pəˈrɪfərəl/",
  "overcurrent info": "/ˈoʊvərˌkʌrənt ˈɪnfoʊ/",
  "inquiry": "/ˈɪŋkwəri/",
  "disturbed": "/dɪˈstɜːrbd/",
  "bluetooth headset": "/ˈbluːtuːθ ˈhedset/",
  "reversing display": "/rɪˈvɜːrsɪŋ dɪˈspleɪ/",
  "noise howling": "/nɔɪz ˈhaʊlɪŋ/",
  "stuck": "/stʌk/",
  "play back": "/pleɪ bæk/",
  "synchronisation": "/ˌsɪŋkrənəˈzeɪʃən/",
  "authorization": "/ˌɔːθərəˈzeɪʃən/",
  "authentication": "/ɔːˌθentɪˈkeɪʃən/",
  "temporarily": "/ˈtempərərəli/",
  "pedestrians": "/pəˈdestriənz/",
  "harness": "/ˈhɑːrnəs/",
  "bracket": "/ˈbrækɪt/",
  "exterior": "/ɪkˈstɪriər/",
  "moderate": "/ˈmɑːdərət/",
  "preliminary": "/prɪˈlɪmɪneri/",
  "initialize": "/ɪˈnɪʃəlaɪz/",
  "serializer": "/ˈsɪriəlaɪzər/",
  "disturbance": "/dɪˈstɜːrbəns/",
  "ethernet": "/ˈiːθərnet/",
  "browse": "/braʊz/",
  "sporadically": "/spəˈrædɪkli/",
  "configuration": "/kənˌfɪɡjəˈreɪʃən/",
  "plugins": "/ˈplʌɡɪnz/",
  "panel": "/ˈpænl/",
  "stakeholder": "/ˈsteɪkhoʊldər/",
  "linux": "/ˈlɪnəks/",
  "implementation": "/ˌɪmplɪmenˈteɪʃən/",
  "archiving": "/ˈɑːrkaɪvɪŋ/",
  "partitions": "/pɑːrˈtɪʃənz/",
  "sequence": "/ˈsiːkwəns/",
  "coordinate": "/koʊˈɔːrdɪneɪt/",
  "moderator": "/ˈmɑːdəreɪtər/",
  "subsystem": "/ˈsʌbsɪstəm/",
  "audio": "/ˈɔːdioʊ/",
  "calendar": "/ˈkælɪndər/",
  "structure": "/ˈstrʌktʃər/",
  "consultation": "/ˌkɑːnsəlˈteɪʃən/",
  "thermal": "/ˈθɜːrməl/",
  "diagnostic": "/ˌdaɪəɡˈnɑːstɪk/",
  "certified": "/ˈsɜːrtɪfaɪd/",
  "variant": "/ˈveriənt/",
  "feature": "/ˈfiːtʃər/",
  "media": "/ˈmiːdiə/",
  "radio": "/ˈreɪdioʊ/",
  "metadata": "/ˈmetədætə/",
  "source": "/sɔːrs/",
  "procedure": "/prəˈsiːdʒər/",
  "respects": "/rɪˈspekts/",
  "minutes": "/ˈmɪnɪts/",
  "capture": "/ˈkæptʃər/",
  "pilot": "/ˈpaɪlət/",
  "reviser": "/rɪˈvaɪzər/",
  "protocol": "/ˈproʊtəkɑːl/",
  "forbearance": "/fɔːrˈberəns/",
  "representative": "/ˌreprɪˈzentətɪv/",
  "parallel": "/ˈpærəlel/",
  "regarding": "/rɪˈɡɑːrdɪŋ/",
  "catalogue": "/ˈkætəlɔːɡ/",
  "mandatory": "/ˈmændətɔːri/",
  "accordance": "/əˈkɔːrdəns/",
  "gateway": "/ˈɡeɪtweɪ/",
  "device": "/dɪˈvaɪs/",
  "nodes": "/noʊdz/",
  "rfq": "/ˌɑːr ef ˈkjuː/",
  "resistor": "/rɪˈzɪstər/",
  "capacitor": "/kəˈpæsɪtər/",
  "voltage": "/ˈvoʊltɪdʒ/",
  "power": "/ˈpaʊər/",
  "supply": "/səˈplaɪ/",
  "ground": "/ɡraʊnd/",
  "noise": "/nɔɪz/",
  "signal": "/ˈsɪɡnəl/",
  "frequency": "/ˈfriːkwənsi/",
  "current": "/ˈkɜːrənt/",
  "charge": "/tʃɑːrdʒ/",
  "oscillator": "/ˈɑːsɪleɪtər/",
  "transistor": "/trænˈzɪstər/",
  "diode": "/ˈdaɪoʊd/",
  "converter": "/kənˈvɜːrtər/",
  "regulator": "/ˈreɡjuleɪtər/",
  "feedback": "/ˈfiːdbæk/",
  "bandwidth": "/ˈbændwɪdθ/",
  "distortion": "/dɪˈstɔːrʃən/",
  "ripple": "/ˈrɪpəl/",
  "threshold": "/ˈθreʃhoʊld/",
  "load": "/loʊd/",
  "output": "/ˈaʊtpʊt/",
  "input": "/ˈɪnpʊt/",
  "channel": "/ˈtʃænl/",
  "module": "/ˈmɑːdʒuːl/",
  "interface": "/ˈɪntərfeɪs/",
  "controller": "/kənˈtroʊlər/",
  "memory": "/ˈmeməri/",
  "register": "/ˈredʒɪstər/",
  "buffer": "/ˈbʌfər/",
  "clock": "/klɑːk/",
  "trigger": "/ˈtrɪɡər/",
  "latency": "/ˈleɪtənsi/",
  "throughput": "/ˈθruːpʊt/",
  "delay": "/dɪˈleɪ/",
  "offset": "/ˈɔːfset/",
  "accuracy": "/ˈækjərəsi/",
  "precision": "/prɪˈsɪʒən/",
  "resolution": "/ˌrezəˈluːʃən/",
  "sampling": "/ˈsæmplɪŋ/",
  "transform": "/trænsˈfɔːrm/",
  "probability": "/ˌprɑːbəˈbɪləti/",
  "variance": "/ˈveriəns/",
  "random": "/ˈrændəm/",
  "phase": "/feɪz/",
  "synchronous": "/ˈsɪŋkrənəs/",
  "differential": "/ˌdɪfəˈrenʃəl/",
  "termination": "/ˌtɜːrmɪˈneɪʃən/",
  "reflection": "/rɪˈflekʃən/",
  "shielding": "/ˈʃiːldɪŋ/",
  "protection": "/prəˈtekʃən/",
};

// ---- 例句词典（覆盖缺失例句的真实英文单词）----
const EXAMPLES = {
  "strong correlation": "There is a strong correlation between temperature and failure rate.",
  "desired": "The system cannot filter the desired high-frequency noise.",
  "pullup resistor": "A pullup resistor keeps the signal line high when not driven.",
  "bias resistor": "The bias resistor sets the operating point of the transistor.",
  "pull down resistor": "A pull down resistor ensures the input reads LOW when idle.",
  "series resistor": "A series resistor limits the current flowing through the LED.",
  "input ac couple capacitor": "The input AC couple capacitor blocks DC offset.",
  "high common mode noise rejection ratio": "A high common mode noise rejection ratio rejects interference.",
  "amplifier": "The amplifier boosts the weak sensor signal to a usable level.",
  "isolation": "Galvanic isolation protects the low-voltage side from high voltage.",
  "beads": "Ferrite beads suppress high-frequency noise on power lines.",
  "capacitor rated voltage": "The capacitor rated voltage must exceed the maximum operating voltage.",
  "dc resistance": "DC resistance is measured in ohms using a multimeter.",
  "impedance": "Match the transmission line impedance to avoid signal reflection.",
  "zener voltage": "The Zener voltage is the stable reverse-breakdown voltage of the diode.",
  "rated power": "Do not exceed the rated power of the resistor.",
  "zener diode": "A Zener diode regulates voltage in reverse breakdown.",
  "relay": "The relay isolates the control circuit from the high-power load.",
  "coil": "The coil stores energy in a magnetic field.",
  "short to battery diagnostic and protection": "Short to battery diagnostic and protection prevents wire damage.",
  "power supply filter capacitor": "The power supply filter capacitor smooths the rectified voltage.",
  "filter": "The low-pass filter removes high-frequency components.",
  "rated voltage": "The rated voltage defines the safe operating limit.",
  "insufficient": "Insufficient decoupling causes power rail instability.",
  "partitioning": "Careful plane partitioning reduces crosstalk between analog and digital.",
  "decoupling capacitor": "Place a decoupling capacitor close to each IC power pin.",
  "non-optimal power plane partitioning": "Non-optimal power plane partitioning increases EMI.",
  "circuit": "The circuit is powered by a regulated 5V supply.",
  "alternative": "An alternative solution is to use a flyback converter.",
  "sync up": "Please sync up with the hardware team before the review.",
  "prior": "This issue was found in prior testing phases.",
  "indication": "The LED gives a clear indication of system status.",
  "capable": "The MCU is capable of processing sensor data in real time.",
  "deficiencies": "We documented several deficiencies in the test report.",
  "innovation": "This innovation reduces boot time by 30 percent.",
  "filed performance": "The filed performance data is stored in the quality database.",
  "field": "The field failure rate is tracked monthly.",
  "determine": "Tests determine whether the module meets the specification.",
  "excitation": "The excitation signal drives the sensor coil.",
  "generated": "The error log is generated automatically on failure.",
  "maintain": "We maintain backward compatibility across releases.",
  "acount": "The user account was created during provisioning.",
  "upgrade": "The OTA upgrade applies the new firmware package.",
  "peripheral": "Each peripheral on the I2C bus has a unique address.",
  "overcurrent info": "The overcurrent info is logged when the limit is exceeded.",
  "inquiry": "The customer inquiry was forwarded to engineering.",
  "disturbed": "The signal was disturbed by electromagnetic interference.",
  "bluetooth headset": "Pair the Bluetooth headset before first use.",
  "reversing display": "The reversing display turns on when reverse gear is engaged.",
  "noise howling": "Audio noise howling occurs when the microphone picks up speaker output.",
  "stuck": "The system got stuck during the bootloader stage.",
  "play back": "The media player can play back both audio and video.",
  "synchronisation": "Time synchronisation keeps all ECUs on the same clock.",
  "authorization": "Authorization is required to access the diagnostic port.",
  "authentication": "Mutual authentication protects the OTA channel.",
  "temporarily": "The service is temporarily unavailable during the update.",
  "pedestrians": "The system detects pedestrians in the vehicle path.",
  "harness": "The wiring harness routes power and signals throughout the vehicle.",
  "bracket": "Mount the module on the bracket using four screws.",
  "exterior": "The exterior camera provides a wide-angle rear view.",
  "moderate": "A moderate temperature range is required for calibration.",
  "preliminary": "The preliminary design review is scheduled for next week.",
  "initialize": "The system will initialize all sensors during boot.",
  "serializer": "The serializer converts parallel data to a serial stream.",
  "disturbance": "Electromagnetic disturbance can cause intermittent failures.",
  "ethernet": "Ethernet carries high-bandwidth camera data in the vehicle.",
  "browse": "Users can browse the media library on the touchscreen.",
  "sporadically": "The fault occurs sporadically and is hard to reproduce.",
  "configuration": "The configuration file defines the active feature set.",
  "plugins": "Third-party plugins extend the infotainment features.",
  "panel": "The control panel shows vehicle status and warnings.",
  "stakeholder": "All stakeholders must approve the design change.",
  "linux": "The ECU runs on an embedded Linux kernel.",
  "implementation": "The implementation phase starts after design approval.",
  "archiving": "Archiving test logs is required for traceability.",
  "partitions": "Flash memory is split into several partitions.",
  "sequence": "The boot sequence initializes safety-critical tasks first.",
  "coordinate": "We coordinate with suppliers to ensure on-time delivery.",
  "moderator": "The moderator facilitated the FMEA workshop.",
  "subsystem": "Each subsystem is validated independently before integration.",
  "audio": "The audio path routes microphone input to the DSP.",
  "calendar": "Check the project calendar for the next milestone.",
  "structure": "The folder structure organizes source by module.",
  "consultation": "After consultation, the team revised the test plan.",
  "thermal": "Thermal management keeps the SoC within safe limits.",
  "diagnostic": "The diagnostic routine reports the fault code.",
  "certified": "The supplier is certified to IATF 16949.",
  "variant": "Each variant has a different feature configuration.",
  "feature": "This feature ships in the next software release.",
  "media": "The media list is indexed on first boot.",
  "radio": "The radio tuner supports FM and DAB bands.",
  "metadata": "Each media file carries metadata such as title and artist.",
  "source": "The fault source is recorded in the log.",
  "procedure": "Follow the procedure for safe firmware flashing.",
  "respects": "In many respects, the new design outperforms the old one.",
  "minutes": "Review the meeting minutes before the next sync.",
  "capture": "The logger captures the last 100 CAN frames.",
  "pilot": "The pilot build validates the production tooling.",
  "reviser": "The reviser checked the spec for accuracy.",
  "protocol": "The diagnostic protocol follows UDS ISO 14229.",
  "forbearance": "The bank granted a forbearance period for repayment.",
  "representative": "Each department sent a representative to the review.",
  "parallel": "Parallel testing validates several features at once.",
  "regarding": "Regarding the schedule slip, please notify the customer.",
  "catalogue": "Look up the part number in the catalogue.",
  "mandatory": "Wearing ESD wrist straps is mandatory in the lab.",
  "accordance": "Testing was done in accordance with ISO 26262.",
  "gateway": "The gateway routes messages between CAN domains.",
  "device": "Each device on the bus has a unique address.",
  "nodes": "All nodes acknowledge the broadcast frame.",
  "rfq": "We sent an RFQ to three qualified suppliers.",
};

// 处理每一行
const lines = src.split('\n');
const out = [];
let statsFoundPron = 0, statsFoundExample = 0, statsSplit = 0;

for (const line of lines) {
  // 匹配单词条目行
  const m = line.match(/^(\s+\{ no:\s*\d+,\s*word:\s*)"((?:[^"\\]|\\.)*)"(,\s*pronunciation:\s*)"((?:[^"\\]|\\.)*)"(,\s*meaning:\s*)"((?:[^"\\]|\\.)*)"(,\s*example:\s*)"((?:[^"\\]|\\.)*)"\s*\},?\s*$/);
  if (!m) { out.push(line); continue; }
  const [, pre, word, mid1, pron, mid2, meaning, mid3, example] = m;
  let finalWord = word;
  let finalPron = pron;
  let finalExample = example;

  // 1) 如果 word 里混了音标（含 /），拆分
  const slashMatch = word.match(/^([A-Za-z][A-Za-z\s\-\.\/]*?)\s*(\/[^\s][^]*\/?)\s*$/);
  if (slashMatch && slashMatch[2].startsWith('/')) {
    finalWord = slashMatch[1].trim();
    finalPron = slashMatch[2].trim();
    statsSplit++;
  }

  // 2) 补音标（如果还没有）
  const key = finalWord.toLowerCase().trim();
  if (!finalPron.trim() && IPA[key]) {
    finalPron = IPA[key];
    statsFoundPron++;
  }

  // 3) 补例句（如果还没有）
  if (!finalExample.trim() && EXAMPLES[key]) {
    finalExample = EXAMPLES[key];
    statsFoundExample++;
  }

  out.push(`${pre}"${finalWord}"${mid1}"${finalPron}"${mid2}"${meaning}"${mid3}"${finalExample}"},`);
}

fs.writeFileSync('src/data/vocabulary.ts', out.join('\n'), 'utf8');
console.log(`✅ Enhanced vocabulary.ts`);
console.log(`   split word/phonetic: ${statsSplit}`);
console.log(`   filled pronunciation: ${statsFoundPron}`);
console.log(`   filled example: ${statsFoundExample}`);
